name = "globalmft-site"
compatibility_date = "2026-03-24"
pages_build_output_dir = "."

[[r2_buckets]]
binding = "CONTACTS_BUCKET" # Este debe ser el nombre exacto que usas en env.CONTACTS_BUCKET
bucket_name = "globalmft-contacts"