name = "globalmft-site"
compatibility_date = "2026-03-24"

# Cloudflare Pages build output
pages_build_output_dir = "."

# R2 bucket para almacenar solicitudes de contacto
[[r2_buckets]]
binding = "GLOBALMFT_CONTACTS"
bucket_name = "globalmft-contacts"
